# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{whistle-ruby}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rich Cavanaugh"]
  s.date = %q{2010-08-20}
  s.description = %q{Whistle notifier for Ruby}
  s.email = %q{rich@withoutscope.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/whistle-ruby.rb",
     "lib/whistle.rb",
     "lib/whistle/configuration.rb",
     "lib/whistle/queuer.rb",
     "lib/whistle/queuer/immediate.rb",
     "lib/whistle/queuer/resque.rb",
     "lib/whistle/sender.rb",
     "test/helper.rb",
     "test/test_configuration.rb"
  ]
  s.homepage = %q{http://github.com/rich/whistle-ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Whistle notifier for Ruby}
  s.test_files = [
    "test/helper.rb",
     "test/test_configuration.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

